CREATE TABLE CUSTOMER(ID CHAR(5), fNAME VARCHAR(25), lNAME VARCHAR(25), PHONE_NO NUMBER(10), AREA CHAR(2));

DESC CUSTOMER;

INSERT INTO CUSTOMER(ID, fNAME, lNAME, PHONE_NO, AREA)VALUES('A01', 'VIJAY', 'PATEL', 9978525226, 'SA');
INSERT INTO CUSTOMER(ID, fNAME, lNAME, PHONE_NO, AREA)VALUES('A02', 'VANDANA', 'SAITWAL', 9978525226, 'MU');
INSERT INTO CUSTOMER(ID, fNAME, lNAME, PHONE_NO, AREA)VALUES('A03', 'PRAMADA', 'JAGUSTE', 9978525226, 'DA');
INSERT INTO CUSTOMER(ID, fNAME, lNAME, PHONE_NO, AREA)VALUES('A04', 'BASU', 'NAVINDGI', 9978525226, 'BA');
INSERT INTO CUSTOMER(ID, fNAME, lNAME, PHONE_NO, AREA)VALUES('A05', 'RAVI', 'SREEDHRAN', 9978525226, 'VA');
INSERT INTO CUSTOMER(ID, fNAME, lNAME, PHONE_NO, AREA)VALUES('A06', 'RUKMINI', '', 9978525226, 'GA');

SELECT * FROM CUSTOMER;

-- CURSORS [EXPLICIT AND IMPLICIT] (25-04-2023)

-- 1. EXPLICIT

DECLARE
    C_ID CUSTOMER.ID%TYPE;
    C_FNAME CUSTOMER.fNAME%TYPE;
    C_PNO CUSTOMER.PHONE_NO%TYPE;
CURSOR C_CUSTOMER IS
    SELECT ID, fNAME, PHONE_NO FROM CUSTOMER;
BEGIN
    OPEN C_CUSTOMER;
    LOOP
        FETCH C_CUSTOMER INTO C_ID, C_FNAME, C_PNO;
        EXIT WHEN C_CUSTOMER%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(C_ID ||' '|| C_FNAME || ' '|| C_PNO);
        END LOOP;
        CLOSE C_CUSTOMER;
END;
