CREATE TABLE CUSTOMER(ID CHAR(5), fNAME VARCHAR(25), lNAME VARCHAR(25), PHONE_NO NUMBER(10), AREA CHAR(2));

DESC CUSTOMER;

INSERT INTO CUSTOMER(ID, fNAME, lNAME, PHONE_NO, AREA)VALUES('A01', 'VIJAY', 'PATEL', 9978525226, 'SA');
INSERT INTO CUSTOMER(ID, fNAME, lNAME, PHONE_NO, AREA)VALUES('A02', 'VANDANA', 'SAITWAL', 9978525226, 'MU');
INSERT INTO CUSTOMER(ID, fNAME, lNAME, PHONE_NO, AREA)VALUES('A03', 'PRAMADA', 'JAGUSTE', 9978525226, 'DA');
INSERT INTO CUSTOMER(ID, fNAME, lNAME, PHONE_NO, AREA)VALUES('A04', 'BASU', 'NAVINDGI', 9978525226, 'BA');
INSERT INTO CUSTOMER(ID, fNAME, lNAME, PHONE_NO, AREA)VALUES('A05', 'RAVI', 'SREEDHRAN', 9978525226, 'VA');
INSERT INTO CUSTOMER(ID, fNAME, lNAME, PHONE_NO, AREA)VALUES('A06', 'RUKMINI', '', 9978525226, 'GA');

SELECT * FROM CUSTOMER;