CREATE TABLE MOVIE(MV_NO NUMBER(5), TITLE VARCHAR(25), TYPE VARCHAR(12), STAR VARCHAR(25), PRICE NUMBER(8, 2));

DESC MOVIE;

INSERT INTO MOVIE(MV_NO, TITLE, TYPE, STAR, PRICE)VALUES(1, 'BLOODY VENGEANCE', 'ACTION', 'JACKIE CHAN', 180.95);

SELECT * FROM MOVIE;