-- CREATING A AFTER TRIGGER;

CREATE OR REPLACE TRIGGER INS_CUSTOMER AFTER INSERT ON CUSTOMER

BEGIN

  DBMS_OUTPUT.PUT_LINE('RECORD INSERTED!');
END;

SELECT * FROM CUSTOMER;

INSERT INTO CUSTOMER VALUES('A07', 'PATEL', 'VIJAY', 381334, 'SA');

-- CREATING A BEFORE TRIGGER;

CREATE OR REPLACE TRIGGER DEL_CUSTOMER BEFORE DELETE ON CUSTOMER

BEGIN
  
  DBMS_OUTPUT.PUT_LINE('RECORD DELETED');
END;

DELETE FROM CUSTOMER WHERE ID = 'A07';

