CREATE TABLE INVOICE(INV_NO CHAR(3), MV_NO NUMBER(5), CUST_ID VARCHAR(5), ISSUE_DATE DATE, RETURN_DATE DATE);

DESC INVOICE;

INSERT INTO INVOICE(INV_NO, MV_NO, CUST_ID, ISSUE_DATE, RETURN_DATE)VALUES('IO1', 3, 'A02', TO_DATE('13-JAN-1996', 'DD-MON-YYYY'), TO_DATE('25-JAN-1996', 'DD-MON-YYYY'));

INSERT INTO INVOICE(INV_NO, MV_NO, CUST_ID, ISSUE_DATE, RETURN_DATE)VALUES('I02', 4, 'A01', TO_DATE('01-FEB-2006', 'DD-MON-YYYY'), TO_DATE('14-FEB-2006', 'DD-MON-YYYY'));

SELECT * FROM INVOICE;
-- WILL DISPLAY THE DATE IN 01/13/1996 FORMAT, I.E MM/DD/YYYY

SELECT INV_NO, MV_NO, CUST_ID, TO_CHAR(ISSUE_DATE, 'DD-MON-YYYY') as ISSUE_DATE, TO_CHAR(RETURN_DATE, 'DD-MON-YYYY') as RETURN_DATE FROM INVOICE; 
-- USED TO DISPLAY DATE IN DD-MON-YYYY FORMAT, E.g: 12-JAN-1996