CREATE TABLE CLIENT_MASTER(CLIENT_NO VARCHAR2(6), NAME VARCHAR2(20), ADDRESS VARCHAR2(100), CITY VARCHAR2(20), PINCODE NUMBER(8), STATE VARCHAR2(20),BAL_DUE NUMBER(10, 2));

DESC CLIENT_MASTER;

INSERT INTO CLIENT_MASTER(CLIENT_NO, NAME, ADDRESS, CITY, PINCODE, STATE, BAL_DUE)VALUES('C0001', 'ROHAN JOSHI', 'KHAPATIYA CHAKLA', 'SURAT', 395003, 'GUJARAT', 15000);

INSERT INTO CLIENT_MASTER(CLIENT_NO, NAME, ADDRESS, CITY, PINCODE, STATE, BAL_DUE)VALUES('C0002', 'MAMTA MAZUMDAR', 'SALT LAKE', 'KOLKATA', 460012, 'WEST BENGAL', 5000);

INSERT INTO CLIENT_MASTER(CLIENT_NO, NAME, ADDRESS, CITY, PINCODE, STATE, BAL_DUE)VALUES('C0003', 'PRANAV SINHA', 'BHUVNESHWARI SOCIETY', 'BARDOLI', 394601, 'GUJARAT', 20000);

SELECT * FROM CLIENT_MASTER;

SELECT * FROM CLIENT_MASTER ORDER BY BAL_DUE DESC;    -- SORTS THE TABLE ACCORDING TO THE BAL_DUE

SELECT * FROM CLIENT_MASTER WHERE STATE='GUJARAT';

SELECT STATE FROM CLIENT_MASTER;           --DISPLAYS THE LIST OF STATES WITH REPEATATION

SELECT DISTINCT STATE FROM CLIENT_MASTER;   --DISPLAYS THE LIST OF STATES WITHOUT REPEATATION

UPDATE CLIENT_MASTER SET CITY = 'SURAT' WHERE CLIENT_NO = 'C0003';       -- CHANGES THE CITY TO 'SURAT'

UPDATE CLIENT_MASTER SET BAL_DUE = 0 WHERE CLIENT_NO = 'C0003';

DELETE FROM CLIENT_MASTER WHERE STATE = 'WEST BENGAL';     -- DELETES EVERY ENTRY WITH WEST BENGAL AS ITS STATE

ALTER TABLE CLIENT_MASTER ADD(MOBILE NUMBER(10));           -- ADDS A NEW COLUMN NAMED MOBILE

UPDATE CLIENT_MASTER SET MOBILE = 9978525226 WHERE CLIENT_NO = 'C0003';     -- SETS MOBILE TO ......

CREATE TABLE BALANCE_DETAILS(CLIENT_NO, NAME, BALANCE) AS SELECT CLIENT_NO, NAME, BAL_DUE FROM CLIENT_MASTER; 
-- CREATES A TABLE NAMED BALANCE_DETAILS AND COPIES THE DATA FROM CLIENT_MASTER TABLE;

DESC BALANCE_DETAILS;

SELECT * FROM BALANCE_DETAILS;

RENAME CLIENT_MASTER TO CUSTOMER_NEW;       -- RENAMES CLIENT_MASTER TO CUSTOMER_NEW;

SELECT * FROM CUSTOMER_NEW;
