CREATE TABLE EMPLOYEE(EMPLOYEE_NO NUMBER(3) PRIMARY KEY, fNAME VARCHAR2(20), lNAME VARCHAR2(20), SALARY NUMBER(8), JOINING_DATE DATE, DEPARTMENT VARCHAR(20));

DESC EMPLOYEE;

INSERT INTO EMPLOYEE(EMPLOYEE_NO, fNAME, lNAME, SALARY, JOINING_DATE, DEPARTMENT)VALUES(1, 'JOHN', 'ABRAHAM', 100000, TO_DATE('01-JAN-2013', 'DD-MON-YYYY'), 'BANKING');
INSERT INTO EMPLOYEE(EMPLOYEE_NO, fNAME, lNAME, SALARY, JOINING_DATE, DEPARTMENT)VALUES(2, 'MICHAEL', 'CLARKE', 80000, TO_DATE('01-APR-2013', 'DD-MON-YYYY'), 'INSURANCE');
INSERT INTO EMPLOYEE(EMPLOYEE_NO, fNAME, lNAME, SALARY, JOINING_DATE, DEPARTMENT)VALUES(3, 'ROY', 'THOMAS', 70000, TO_DATE('21-MAY-2013', 'DD-MON-YYYY'), 'BANKING');
INSERT INTO EMPLOYEE(EMPLOYEE_NO, fNAME, lNAME, SALARY, JOINING_DATE, DEPARTMENT)VALUES(4, 'TOM', 'JOSE', 60000, TO_DATE('08-DEC-2013', 'DD-MON-YYYY'), 'BANKING');
INSERT INTO EMPLOYEE(EMPLOYEE_NO, fNAME, lNAME, SALARY, JOINING_DATE, DEPARTMENT)VALUES(5, 'PRANAV', 'SINHA', 40000, TO_DATE('08-DEC-2013', 'DD-MON-YYYY'), 'BANKING');
INSERT INTO EMPLOYEE(EMPLOYEE_NO, fNAME, lNAME, SALARY, JOINING_DATE, DEPARTMENT)VALUES(6, 'THOMAS', 'SHELBY', 60000, TO_DATE('08-DEC-2013', 'DD-MON-YYYY'), 'BANKING');

SELECT * FROM EMPLOYEE; 

SELECT * FROM EMPLOYEE ORDER BY FNAME ASC;            -- Arranges the first names into ascending order
SELECT * FROM EMPLOYEE ORDER BY FNAME DESC;            -- Arranges the first names into descending order
SELECT * FROM EMPLOYEE ORDER BY FNAME ASC, SALARY DESC;          -- Arranges the first names into ASCENDING order AND salary into descending

CREATE TABLE INCENTIVES(EMP_REF_ID NUMBER(3), INC_DATE DATE, AMT NUMBER(5), FOREIGN KEY (EMP_REF_ID) REFERENCES EMPLOYEE);

DESC INCENTIVES;

INSERT INTO INCENTIVES(EMP_REF_ID, INC_DATE, AMT)VALUES(1, TO_DATE('01-FEB-2013', 'DD-MON-YY'), 5000);
INSERT INTO INCENTIVES(EMP_REF_ID, INC_DATE, AMT)VALUES(2, TO_DATE('01-DEC-2013', 'DD-MON-YY'), 3000);
INSERT INTO INCENTIVES(EMP_REF_ID, INC_DATE, AMT)VALUES(3, TO_DATE('01-MAR-2013', 'DD-MON-YY'), 4000);
INSERT INTO INCENTIVES(EMP_REF_ID, INC_DATE, AMT)VALUES(4, TO_DATE('21-MAR-2013', 'DD-MON-YY'), 4500);

SELECT * FROM INCENTIVES;

SELECT fNAME, lNAME FROM EMPLOYEE;

SELECT fNAME "EMPLOYEE_NAME" FROM EMPLOYEE;

SELECT LOWER(fNAME) FROM EMPLOYEE;

SELECT UPPER(fNAME) FROM EMPLOYEE;

SELECT DISTINCT DEPARTMENT FROM EMPLOYEE;
