CREATE TABLE DEPARTMENT(DEPT_NO NUMBER(3) PRIMARY KEY, DNAME VARCHAR2(15), LOC VARCHAR2(15));

DESC DEPARTMENT;

INSERT INTO DEPARTMENT(DEPT_NO, DNAME, LOC)VALUES(10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPARTMENT(DEPT_NO, DNAME, LOC)VALUES(20, 'RESEARCH', 'DALLAS');
INSERT INTO DEPARTMENT(DEPT_NO, DNAME, LOC)VALUES(30, 'SALES', 'CHICAGO');
INSERT INTO DEPARTMENT(DEPT_NO, DNAME, LOC)VALUES(40, 'OPERATIONS', 'BOSTON');

SELECT * FROM DEPARTMENT;
